In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('raw_data.csv')

# cleaning data

#1. missing value

df.isnull()     # returns true if any data is not given or empty.
df.isna()       # both isnull and isna have same work

df.isnull().sum()       # returns how many values are missing per column

df.dropna()     # drop the raw if any value in the raw is empty

df.dropna(axis=1)   # drop col

df.fillna(0)    # replace empty vl with 0. we can use anything instead of 0
# age_mean = df['age'].mean()
# df['age'].fillna(age_mean)      # replacing the empty ages with avg val of remaining ages

cleaned_data = df.copy()        # we generally use copy data
age_mean = cleaned_data['age'].mean()
cleaned_data['age'] = cleaned_data['age'].fillna(age_mean) 
cleaned_data


df.ffill()      # fill the previous data at the curr empty val
df.bfill        # fill the next data at the curr empty val

<bound method NDFrame.bfill of     id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0>

In [4]:
#2 Deduplication

df['country'].duplicated()      # returns true if get any repeated val/data
df[['country','gender']].duplicated()   # can check in two col

df.drop_duplicates()        # does not change in original data

# df2 = df.copy()
# df.drop_duplicates(inplace=True)        # inplace = true changes in original data but it is not suggested. If we do changes in original data then we must have a copy of original data so that our original data does not lost

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [5]:
#3 Handling data type - we use two methods 
# (a)df.dtype   (b)df.astype(newtype)
df.dtypes

df2 = df.copy()

df2 = df2.fillna(0)
df2['age'] = df2['age'].astype('int64')     # we can say that we doing type conversion with the help of astype()
df2.dtypes
df2

# handle date-time data- we use to_datetime() method

aqi_data = pd.read_csv('globalAirQuality.csv')
aqi_data

aqi_data['timestamp'] = pd.to_datetime(aqi_data['timestamp'])

aqi_data['timestamp'].astype


data_str = pd.Series([pd.to_datetime('12-03-2025')])
type(data_str.dtypes)

numpy.dtypes.DateTime64DType

In [ ]:
# handle strings- we use following methods to handle the strings

# (a) .str.lower(), .str.upper() & .str.capitalize()
# (b) .str.strip()
# (c) .str.split('')    // divides the str from separator(char passes inside the split)
# (d) .str.contains(val, case=False)

df['gender'].str.lower()
df['gender'].str.upper()

df['name'].str.split(' ')

df['country'].str.contains('US', case=False)    # case=False ignores the lower and upper cases

0      True
1      True
2     False
3      True
4     False
5     False
6     False
7       NaN
8      True
9     False
10     True
Name: country, dtype: object

In [7]:
# df = df2
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0