In [2]:
import pandas as pd

In [10]:


df = pd.DataFrame({
    'country':['USA','USA','India','India'],
    'year': [2020,2021,2020,2021],
    'sales': [100,120,90,110],
    'profit': [20,25,18,22],
})


# melt - Wide to long format, (before: rows<col, after: rows>col)

# melt(id_vars, value_vars, var_name, value_name)
# id_vars - what are the cols we want to store
# value_vars - what are the cols whose value we want in single col
# var_name - what will be the name of new combined col
# value_name - where our new val wi store

melted_df = df.melt(
    id_vars=['country','year'],
    value_vars=['sales','profit'],
    var_name='metrics',
    value_name='value'
)

In [ ]:
# pivot - Long to wide format (before: rows>col, after: rows<cols)

original = melted_df.pivot(
    index=['country','year'],        # country and year is to be labelled.
    columns='metrics',      # metrics val will convert into col
    values='value'
)
original

metrics       profit  sales
country year
India   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120

In [6]:
df

  country  year  sales  profit  tax
0     USA  2020    100      20   10
1     USA  2021    120      25   20
2   India  2020     90      18   30
3   India  2021    110      22   40