In [1]:
import pandas as pd

In [2]:
#  Transforming data (Feature Engineering) - means which feature we have to select or add

# (a) apply()       // when write a transform logic inside a func then we use apply func under which pass that func as para
# (b) map()         // change the existing feature
# (c) assign()      // create new policy
# (d) replace(old,new)

df = pd.read_csv('raw_data.csv')

df2 = df.copy()
df2
df2['tax'] = df2['income'].apply(lambda x: "20%" if x>=50_000 else '10%')

gender_map = {'Male':'M', 'Female':'F', 'Unknown':'U'}
df2['gender'] = df2['gender'].map(gender_map)

df2 = df2.assign(new_income = df2['income']*2)

df2['country'] = df2['country'].replace('USA','US')
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0      US      M  55000.0  20%    110000.0
1    1      John Doe  29.0      US      M  55000.0  20%    110000.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%    124000.0
3    3          Alex   NaN      US      U  47000.0  10%     94000.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  20%    102000.0
6    6           NaN  45.0   India      F  73000.0  20%    146000.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%    136000.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%    124000.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     90000.0
10  10   Emily Davis  31.0      US    NaN  58000.0  20%    116000.0

In [12]:
# some more methods
df2.columns = ['ID','Name','Age','Country','Gender','Income','Tax','New_Income'] # change all the columns name

df2.rename(columns={'Income':'Salary'})
# df2.rename(index={1:'First'})
df2.sort_values('Income')
df2.sort_values('Income', ascending=False)

df2.sort_values(['Income','Age'])     # if income is same then it checks age

# reset
sorted_df = df2.sort_values('Income')

sorted_df.reset_index()     # brings new idx starts from 0 but old idx is preserved
sorted_df.reset_index(drop=True)    # old idx is removed now

# ranking
sorted_df['Ranking'] = sorted_df['Income'].rank()   # ties of or more val takes the average so rank may comes in float
sorted_df['Ranking'] = sorted_df['Income'].rank(method='dense')    # can also use min and max instead of dense 

# reorder
sorted_df[['ID','Name','Age','Country','Gender','Income','New_Income','Tax']]

    ID          Name   Age Country Gender   Income  New_Income  Tax
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0     90000.0  10%
3    3          Alex   NaN      US      U  47000.0     94000.0  10%
5    5        Li Wei  27.0   China      M  51000.0    102000.0  20%
0    1      John Doe  29.0      US      M  55000.0    110000.0  20%
1    1      John Doe  29.0      US      M  55000.0    110000.0  20%
10  10   Emily Davis  31.0      US    NaN  58000.0    116000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0    124000.0  20%
8    8    Rachel Lee  29.0      US      F  62000.0    124000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0    136000.0  20%
6    6           NaN  45.0   India      F  73000.0    146000.0  20%
4    4  Maria Garcia  34.0   Spain      F      NaN         NaN  10%